fix(repository): correct types in juggler bridge
Fix the following problem reported by `npm pack`:

Error: packages/repository/src/legacy-juggler-bridge.ts(100)
  Type 'typeof ModelBase' is not assignable to
  type 'typeof PersistedModel'.
  Property 'create' is missing in type 'typeof ModelBase'.