Update todo-tutorial-putting-it-together.md
If use
```
import {db} from './datasources/db.datasource';
```
then
```
make error src/application.ts(4,9): error TS2305: Module '"/src/datasources/db.datasource"' has no exported member 'db'
```
because src/datasources/db.datasource export DbDataSource not 'db'

so you 
```
 import {DbDataSource} from './datasources/db.datasource';
```
and
```
 const datasource =
      this.options && this.options.datasource
        ? new juggler.DataSource(this.options.datasource)
        : DbDataSource;
```