fix(cli): exclude json files from tslint
tslint complains:
ERROR: examples/soap-calculator/src/datasources/calculator.datasource.json[1, 1]:
unused expression, expected an assignment or function call