fix(cli): remove project references from examples
In strongloop/loopback-next#5155, we reworked our typescript setup
to leverage composite mode and project references. This breaks our
example applications when they are checked out standalone, typically
via `lb4 example`.

```sh
$ lb4 example todo
(...)
$ cd loopback4-example-todo
$ npm t
(...)
> lb-tsc

error TS6053: File '/private/packages/http-caching-proxy/tsconfig.json' not found.
error TS6053: File '/private/packages/testlab/tsconfig.json' not found.
(...)
Found 10 errors.
```

This commit fixes the problem by introducing a new step to `lb4 example`
command where we remove `references` field from `tsconfig.json` file
and set the field `compilerOptions.composite` to `false`.

Signed-off-by: Miroslav Bajtoš <mbajtoss@gmail.com>