docs: add missing imports for getting started docs
It fixes the following error:
```
src/application.ts(11,42): error TS4020: 'extends' clause of exported
class 'CarizhenApplication' has or is using private name 'juggler.DataSource'.
```